names = ['liwai','cl','ch','lsq']
print(names[0])
print(names[1])
print(names[2])
print(names[3])
print(names[0] +',How are you?')
print(names[1] +',How are you?')
print(names[2] +',How are you?')
print(names[3] +',How are you?')
print(names[0]+'，你愿意和我共进晚餐吗？')
print(names[1]+'，你愿意和我共进晚餐吗？')
print(names[2]+'，你愿意和我共进晚餐吗？')
print(names[3]+'，你愿意和我共进晚餐吗？')
print(names[0]+'无法赴约')
names[0] = 'chlsp'
print(names[0]+'，你愿意和我共进晚餐吗？')
print(names[1]+'，你愿意和我共进晚餐吗？')
print(names[2]+'，你愿意和我共进晚餐吗？')
print(names[3]+'，你愿意和我共进晚餐吗？')
print('我找到了更大的餐桌')
names.insert(0,'ff')
names.insert(3,'ww')
names.append('kk')
print(names[0]+'，你愿意和我共进晚餐吗？')
print(names[1]+'，你愿意和我共进晚餐吗？')
print(names[2]+'，你愿意和我共进晚餐吗？')
print(names[3]+'，你愿意和我共进晚餐吗？')
print(names[4]+'，你愿意和我共进晚餐吗？')
print(names[5]+'，你愿意和我共进晚餐吗？')
print(names[6]+'，你愿意和我共进晚餐吗？')
print('我只能邀请两位嘉宾共进晚餐')
popped_name0 = names.pop(0)
print('对不起，不能和你共进晚餐了'+ popped_name0)
popped_name1 = names.pop(0)
print('对不起，不能和你共进晚餐了'+ popped_name1)
popped_name2 = names.pop(0)
print('对不起，不能和你共进晚餐了'+ popped_name2)
popped_name3 = names.pop(0)
print('对不起，不能和你共进晚餐了'+ popped_name3)
popped_name4 = names.pop(0)
print('对不起，不能和你共进晚餐了'+ popped_name4)
print(names[0]+'你还在邀请之列')
print(names[1]+'你还在邀请之列')
del names[0]
del names[0]
print(names)
len(names)
print(len(names))