nation = ['china','america','england','france','russia']
print(nation[0])
print(nation[0].title())
print(nation[-1])
message = 'my moutherland is '+ nation[0].title()
print(message)
nation[-1] = 'korea'
print(nation)
nation.append('russia')
print(nation)
nation.insert(1,'australia')
del nation[-1]
print(nation)
nation.pop(-1)
print(nation)
nation.remove('england')
print(nation)
nation.sort()
print(nation)
nation.sort(reverse=True)
print(nation)
print(sorted(nation))
nation.reverse()
print(nation)
print(len(nation))
